### ISSUE TITLE
Parse more stuff from QC sample info

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/pymip#23]
- [ ] rank model version (Clinical-Genomics/scout#150)
- [ ] rank model file (Clinical-Genomics/scout#153)
- [ ] gene list files (Clinical-Genomics/scout#162)
- [ ] analysis type (Clinical-Genomics/scout#151)
